const RESULT_ENDPOINT = 'https://script.google.com/macros/s/AKfycbyOsnfvzDlbRNXpWzbNNEdDR0cRfL7F_C8E0ZPlv-Cd3EKIDnQ0zQGOqe1uX9LP_yBW/exec';
const QUESTIONS_PER_TEST = 50;
const TEST_MINUTES = 60;
let state={name:'',email:'',code:'',role:'',questions:[],answers:{},current:0,startedAt:null,endAt:null,timerHandle:null,submitted:false,adminTest:false};
const $=id=>document.getElementById(id);
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function getBankKey(role){return role==='Primary 3 Teacher'?'primary':role==='ICT Teacher'?'ict':role==='Office Assistant'?'office':null;}
function startTest(){
 const name=$('candidateName').value.trim(),email=$('candidateEmail').value.trim().toLowerCase(),code=$('candidateCode').value.trim(),role=$('candidateRole').value;
 state.adminTest=new URLSearchParams(location.search).get('adminTest')==='1' || sessionStorage.getItem('LC_ADMIN_TEST')==='1';
 $('startError').textContent='';
 if(!name||!email||!code||!role){$('startError').textContent='Please complete all fields.';return;}
 if(!state.adminTest && !/^\d{6}$/.test(code)){$('startError').textContent='Enter the 6-digit CBT access code supplied to you.';return;}
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){$('startError').textContent='Please enter a valid email address.';return;}
 const bank=window.QUESTION_BANKS[getBankKey(role)]; if(!bank||bank.length<QUESTIONS_PER_TEST){$('startError').textContent='The question bank for this position is unavailable.';return;}
 state.questions=shuffle(bank).slice(0,QUESTIONS_PER_TEST).map(q=>{const opts=shuffle(q.options);return {...q,options:opts,answer:opts.indexOf(q.options[q.answer])};});
 if(state.adminTest){ const r=new URLSearchParams(location.search).get('role')||sessionStorage.getItem('LC_ADMIN_ROLE')||role; state.role=r; $('candidateRole').value=r; } else { state.role=role; }
 state.name=name;state.email=email;state.code=code;state.current=0;state.answers={};state.startedAt=new Date();state.endAt=new Date(Date.now()+TEST_MINUTES*60000);
 $('startScreen').classList.add('hidden');$('testScreen').classList.remove('hidden');$('roleDisplay').textContent=role;renderQuestion();startTimer();
}
function renderQuestion(){const q=state.questions[state.current];$('questionNumber').textContent=`Question ${state.current+1} of ${state.questions.length}`;$('progress').textContent=`${Object.keys(state.answers).length} answered`;$('questionText').textContent=q.question;const options=$('options');options.innerHTML='';q.options.forEach((option,i)=>{const label=document.createElement('label');label.className='option';const radio=document.createElement('input');radio.type='radio';radio.name='answer';radio.value=i;radio.checked=state.answers[q.id]===i;radio.addEventListener('change',()=>{state.answers[q.id]=i;updatePalette();$('progress').textContent=`${Object.keys(state.answers).length} answered`;});const text=document.createElement('span');text.textContent=`${String.fromCharCode(65+i)}. ${option}`;label.append(radio,text);options.appendChild(label);});$('prevBtn').disabled=state.current===0;$('nextBtn').textContent=state.current===state.questions.length-1?'Submit Test':'Next';updatePalette();}
function updatePalette(){const p=$('questionPalette');p.innerHTML='';state.questions.forEach((q,i)=>{const b=document.createElement('button');b.className='pal';if(state.answers[q.id]!==undefined)b.classList.add('answered');if(i===state.current)b.classList.add('current');b.textContent=i+1;b.addEventListener('click',()=>{state.current=i;renderQuestion();window.scrollTo({top:0,behavior:'smooth'});});p.appendChild(b);});}
function nextQuestion(){if(state.current===state.questions.length-1){submitTest(false);return;}state.current++;renderQuestion();window.scrollTo({top:0,behavior:'smooth'});}
function previousQuestion(){if(state.current>0){state.current--;renderQuestion();window.scrollTo({top:0,behavior:'smooth'});}}
function startTimer(){clearInterval(state.timerHandle);function tick(){const remaining=Math.max(0,state.endAt-Date.now());const totalSeconds=Math.floor(remaining/1000),minutes=Math.floor(totalSeconds/60),seconds=totalSeconds%60;$('timer').textContent=`${String(minutes).padStart(2,'0')}:${String(seconds).padStart(2,'0')}`;if(remaining<=0){clearInterval(state.timerHandle);submitTest(true);}}tick();state.timerHandle=setInterval(tick,1000);}
function submitTest(autoSubmitted){if(state.submitted)return;const unanswered=state.questions.length-Object.keys(state.answers).length;if(!autoSubmitted&&unanswered>0&&!confirm(`You have ${unanswered} unanswered question(s). Submit anyway?`))return;state.submitted=true;clearInterval(state.timerHandle);const responses=state.questions.map(q=>({id:q.id,question:q.question,selected:state.answers[q.id]===undefined?null:state.answers[q.id],correct:q.answer}));const correct=responses.filter(r=>r.selected!==null&&r.selected===r.correct).length;const percentage=Math.round((correct/state.questions.length)*10000)/100;const timeRemainingSeconds=Math.max(0,Math.floor((state.endAt-Date.now())/1000));const payload={candidateName:state.name,email:state.email,accessCode:state.code,role:state.role,score:correct,total:state.questions.length,percentage,unanswered,autoSubmitted,startedAt:state.startedAt.toISOString(),submittedAt:new Date().toISOString(),timeRemainingSeconds,responses};$('testScreen').classList.add('hidden');$('completeScreen').classList.remove('hidden');$('completionText').textContent=state.adminTest?'Administrator test mode completed. No candidate result was recorded.':'Your test has been submitted. Please remain available for further instructions.';if(state.adminTest)return;if(!RESULT_ENDPOINT)return;fetch(RESULT_ENDPOINT,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({data:JSON.stringify({action:'submit',...payload})})}).catch(()=>{});}
$('startBtn').addEventListener('click',startTest);$('nextBtn').addEventListener('click',nextQuestion);$('prevBtn').addEventListener('click',previousQuestion);
